import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { AppHeader } from "@/components/general/header/AppHeader";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/general/sidebar/AppSidebar";

export const metadata: Metadata = {
   title: "Voulquant",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className="">
            <SidebarProvider>
               <AppSidebar />
               <main className="w-full">
                  <AppHeader />
                  {children}
               </main>
            </SidebarProvider>
         </body>
      </html>
   );
}
